name: CI

on:
  push:
    branches: [ main ]
    pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 18
      - name: clean build
        run: ./gradlew clean build --info --stacktrace